# Generated by Django 5.2.7 on 2026-06-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0002_product_prix_promo_product_promo_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieQuincaillerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('icone', models.CharField(blank=True, max_length=100)),
                ('categorie_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quicaillerie.categoriequincaillerie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitQuincaillerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('unite', models.CharField(default='Pièce', max_length=50)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion')], default='neuf', max_length=20)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('garantie', models.CharField(blank=True, max_length=100)),
                ('livraison_disponible', models.BooleanField(default=True)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('rupture', 'Rupture de stock'), ('precommande', 'Précommande')], default='disponible', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_quincaillerie', to='shopping.shop')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quicaillerie.categoriequincaillerie')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopping/products/images/')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='0 = image principale')),
                ('principale', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_quincaillerie', to='shopping.couleur')),
                ('tailles', models.ManyToManyField(blank=True, related_name='product_quincaillerie', to='shopping.taille')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='quicaillerie.produitquincaillerie')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
