# Generated by Django 5.2.7 on 2025-11-03 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_serviceimage_servicetexte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commande', models.CharField(editable=False, help_text='Code unique généré automatiquement', max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_appliquee', models.DecimalField(decimal_places=2, default=0.0, help_text='Remise en % appliquée sur la commande', max_digits=5)),
                ('mode_paiement', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], max_length=50, null=True)),
                ('notes_client', models.TextField(blank=True, help_text='Commentaires ou précisions du client', null=True)),
                ('notes_interne', models.TextField(blank=True, help_text="Notes internes visibles par l'équipe uniquement", null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='services.service')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='commandes/')),
                ('type_fichier', models.CharField(choices=[('document_client', 'Document client'), ('livrable', 'Livrable final'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('nom_original', models.CharField(blank=True, max_length=255, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('taille', models.PositiveIntegerField(blank=True, help_text='Taille du fichier en octets', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Fichier de commande',
                'verbose_name_plural': 'Fichiers de commande',
                'ordering': ['-date_upload'],
            },
        ),
    ]
