# Generated by Django 5.2.7 on 2025-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_order_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='resultats',
            field=models.ManyToManyField(blank=True, help_text='Fichiers livrés au client (résultats finaux)', related_name='commandes_resultats', to='commandes.orderfile'),
        ),
    ]
