# Generated by Django 5.2.7 on 2025-11-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_order_resultats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Nom lisible du fichier livré', max_length=255, null=True)),
                ('fichier', models.FileField(upload_to='resultats_commandes/')),
                ('commentaire', models.TextField(blank=True, help_text='Détails ou explications du travail effectué', null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Fichier résultat',
                'verbose_name_plural': 'Fichiers résultats',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
