# Generated by Django 5.2.7 on 2025-11-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_resultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('en_attente', 'En attente de traitement'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
