# Generated by Django 5.2.7 on 2026-06-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('employe', 'Employé'), ('livreur', 'Livreur')], default='client', max_length=20),
        ),
    ]
