# Generated by Django 5.2.7 on 2026-06-11 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_user_last_lat_user_last_lng_user_last_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('employe', 'Employé'), ('livreur', 'Livreur'), ('vendeur', 'Vendeur')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='VendeurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('resto', 'Restaurant'), ('marche', 'Marché'), ('shopping', 'Shopping'), ('perruque', 'Perruque & Beauté'), ('voiture', 'Location Voiture'), ('immobilier', 'Immobilier'), ('quicaillerie', 'Quincaillerie')], max_length=30, verbose_name='Section')),
                ('nom_commercial', models.CharField(blank=True, max_length=200, verbose_name='Nom commercial')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendeurs/logos/')),
                ('telephone_pro', models.CharField(blank=True, max_length=20, verbose_name='Téléphone professionnel')),
                ('email_pro', models.EmailField(blank=True, max_length=254, verbose_name='Email professionnel')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ventes', models.PositiveIntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Vendeur',
                'verbose_name_plural': 'Profils Vendeurs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('resto', 'Restaurant'), ('marche', 'Marché'), ('shopping', 'Shopping'), ('perruque', 'Perruque'), ('voiture', 'Location Voiture'), ('immobilier', 'Immobilier'), ('quicaillerie', 'Quincaillerie')], max_length=20, verbose_name='Section')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID commande')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Sous-total')),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais livraison')),
                ('frais_service', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais service')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total')),
                ('methode', models.CharField(choices=[('especes', 'Espèces'), ('airtel_money', 'Airtel Money'), ('mtn_mobile', 'MTN Mobile Money'), ('orange_money', 'Orange Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], default='especes', max_length=30, verbose_name='Méthode')),
                ('fournisseur', models.CharField(blank=True, max_length=60, verbose_name='Fournisseur')),
                ('reference_externe', models.CharField(blank=True, max_length=200, verbose_name='Référence externe')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_livraison', models.CharField(choices=[('livraison', 'Livraison'), ('retrait', 'Retrait en boutique')], default='livraison', max_length=20, verbose_name='Mode')),
                ('quartier_livraison', models.CharField(blank=True, max_length=100, verbose_name='Quartier')),
                ('adresse_livraison', models.TextField(blank=True, verbose_name='Adresse exacte')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('valide_le', models.DateTimeField(blank=True, null=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['statut'], name='users_paiem_statut_dea09f_idx'), models.Index(fields=['section', '-cree_le'], name='users_paiem_section_d189c8_idx'), models.Index(fields=['client', '-cree_le'], name='users_paiem_client__fc5f4e_idx')],
            },
        ),
    ]
