# Generated by Django 5.2.15 on 2026-06-12 10:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_vendeur_profile_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log position',
                'verbose_name_plural': 'Logs positions',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='users_userp_user_id_142067_idx')],
            },
        ),
    ]
