# Generated by Django 5.2.15 on 2026-06-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_livraison_gps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='livraison',
            new_name='users_livra_statut_a304dc_idx',
            old_name='livraison_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='livraison',
            new_name='users_livra_livreur_885e50_idx',
            old_name='livraison_livreur_statut_idx',
        ),
        migrations.AddField(
            model_name='paiement',
            name='telephone_paiement',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone mobile money'),
        ),
    ]
