# Generated by Django 5.2.15 on 2026-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_paiement_telephone_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matricule',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Matricule'),
        ),
    ]
