# Generated by Django 5.2.15 on 2026-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='livreur_nom_cache',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom livreur (cache)'),
        ),
    ]
