# Generated by Django 5.2.7 on 2026-06-11 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0002_product_prix_promo_product_promo_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('studio', 'Studio'), ('villa', 'Villa'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('commerce', 'Local commercial'), ('entrepot', 'Entrepôt')], max_length=30, verbose_name='Type de bien')),
                ('type_offre', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=20, verbose_name="Type d'offre")),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix')),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix promotionnel')),
                ('description', models.TextField(verbose_name='Description')),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)')),
                ('nombre_chambres', models.PositiveIntegerField(default=0, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.PositiveIntegerField(default=0, verbose_name='Nombre de salles de bain')),
                ('nombre_salons', models.PositiveIntegerField(default=0, verbose_name='Nombre de salons')),
                ('nombre_cuisines', models.PositiveIntegerField(default=0, verbose_name='Nombre de cuisines')),
                ('nombre_garages', models.PositiveIntegerField(default=0, verbose_name='Nombre de garages')),
                ('meuble', models.BooleanField(default=False, verbose_name='Meublé')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.CharField(max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu', 'Vendu'), ('loue', 'Loué')], default='disponible', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='shopping.shop', verbose_name='Agence / Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immobilier/photos/', verbose_name='Photo')),
                ('principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobilier.immobilier')),
            ],
        ),
        migrations.CreateModel(
            name='VideoImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='immobilier/videos/', verbose_name='Vidéo')),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='immobilier.immobilier')),
            ],
        ),
    ]
