# Generated by Django 5.2.15 on 2026-06-11 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmobilierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône emoji')),
            ],
            options={
                'verbose_name': 'Catégorie immobilier',
                'verbose_name_plural': 'Catégories immobilier',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='immobilier',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Bien immobilier', 'verbose_name_plural': 'Biens immobiliers'},
        ),
        migrations.AlterModelOptions(
            name='photoimmobilier',
            options={'ordering': ['ordre', 'date_creation'], 'verbose_name': 'Photo du bien', 'verbose_name_plural': 'Photos du bien'},
        ),
        migrations.AddField(
            model_name='immobilier',
            name='annee_construction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de construction'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='climatisation',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='eau_courante',
            field=models.BooleanField(default=True, verbose_name='Eau courante'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='etage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Laisser vide pour maison / villa / terrain.', null=True, verbose_name='Étage (appartement)'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='gardien',
            field=models.BooleanField(default=False, verbose_name='Gardien'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='generatrice',
            field=models.BooleanField(default=False, verbose_name='Groupe électrogène'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='piscine',
            field=models.BooleanField(default=False, verbose_name='Piscine'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='promo_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début promotion'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='promo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin promotion'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
        ),
        migrations.AddField(
            model_name='photoimmobilier',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='adresse',
            field=models.CharField(max_length=255, verbose_name='Adresse / Quartier'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='nombre_chambres',
            field=models.PositiveIntegerField(default=0, verbose_name='Chambres'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='nombre_cuisines',
            field=models.PositiveIntegerField(default=0, verbose_name='Cuisines'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='nombre_garages',
            field=models.PositiveIntegerField(default=0, verbose_name='Garages'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='nombre_salles_bain',
            field=models.PositiveIntegerField(default=0, verbose_name='Salles de bain'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='nombre_salons',
            field=models.PositiveIntegerField(default=0, verbose_name='Salons'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='prix_promotionnel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix promotionnel (FCFA)'),
        ),
        migrations.CreateModel(
            name='DemandeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souhaitee', models.DateField(verbose_name='Date souhaitée')),
                ('heure_souhaitee', models.TimeField(blank=True, null=True, verbose_name='Heure souhaitée')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone de contact')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('done', 'Effectuée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite', to='immobilier.immobilier', verbose_name='Bien')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_visite_immo', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Demande de visite',
                'verbose_name_plural': 'Demandes de visite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='immobilier',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biens', to='immobilier.immobiliercategory', verbose_name='Catégorie'),
        ),
    ]
