# Generated by Django 5.2.7 on 2026-06-12 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0003_alter_immobilier_vendeur'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='immobilier',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='immobilier',
            name='longitude',
        ),
        migrations.AddField(
            model_name='immobilier',
            name='caution',
            field=models.CharField(blank=True, max_length=100, verbose_name='caution (ex: 1 mois de loyer)'),
        ),
        migrations.AddField(
            model_name='immobilier',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartier', to='location.quartier', verbose_name='Agence / Propriétaire'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ville', to='location.ville', verbose_name='Agence / Propriétaire'),
        ),
    ]
