# Generated by Django 5.2.7 on 2025-11-05 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0004_resultfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_transaction', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XAF', help_text='Devise du paiement', max_length=10)),
                ('mode', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('espece', 'Espèces')], max_length=30)),
                ('reference_transaction', models.CharField(editable=False, max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, help_text='Informations supplémentaires sur la transaction', null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('recu_url', models.URLField(blank=True, help_text='Lien vers le reçu de paiement (si disponible)', null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(editable=False, max_length=50, unique=True)),
                ('pdf_url', models.URLField(blank=True, help_text='Lien vers le fichier PDF de la facture', null=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total facturé', max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=0.0, help_text='TVA en pourcentage', max_digits=5)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('signature_admin', models.CharField(blank=True, max_length=255, null=True)),
                ('valide', models.BooleanField(default=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='paiements.payment')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
