# Generated by Django 5.2.7 on 2025-11-07 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('categorie', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('systeme', 'Système'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('action', models.CharField(help_text='Description courte de l’action effectuée', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Détails supplémentaires sur l’action', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Navigateur / client utilisé', max_length=255, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('succes', models.BooleanField(default=True, help_text='Indique si l’action s’est déroulée sans erreur')),
                ('objet_concerne', models.CharField(blank=True, help_text='Nom de l’objet ou ressource ciblée', max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-date_action'],
                'indexes': [models.Index(fields=['categorie'], name='activityLog_categor_de6d27_idx'), models.Index(fields=['user'], name='activityLog_user_id_40c55c_idx'), models.Index(fields=['date_action'], name='activityLog_date_ac_ade0b0_idx')],
            },
        ),
    ]
