# Generated by Django 5.2.7 on 2026-06-09 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['ville', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=200)),
                ('type_commerce', models.CharField(choices=[('marche', 'Faire le marché'), ('shopping', 'Shopping'), ('quincaillerie', 'Quincaillerie'), ('perruques', 'Perruques & beauté'), ('electronique', 'Électronique'), ('mode', 'Mode'), ('pharmacie', 'Pharmacie'), ('restaurant', 'Restaurant'), ('elevage', 'Élevage'), ('autre', 'Autre')], default='marche', max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('nom_marche', models.CharField(blank=True, help_text='Si marché non listé', max_length=200)),
                ('stand', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marche/vendeurs/')),
                ('description', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='marche.marche')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('unite', models.CharField(default='pièce', help_text='kg, litre, pièce…', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marche/produits/')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('disponibilite', models.BooleanField(default=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='marche.categorie')),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='marche.marche')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='marche.vendeur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
    ]
