# Generated by Django 5.2.7 on 2026-06-09 13:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('marche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marche',
            options={'ordering': ['nom'], 'verbose_name': 'Marché', 'verbose_name_plural': 'Marchés'},
        ),
        migrations.RemoveField(
            model_name='marche',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='longitude',
        ),
        migrations.AddField(
            model_name='marche',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Position GPS du marché (point central)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Position GPS du stand / de la boutique', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='marche',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches', to='location.commune'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches', to='location.quartier'),
        ),
        migrations.AlterField(
            model_name='marche',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches', to='location.ville'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite',
            field=models.CharField(default='pièce', max_length=50),
        ),
        migrations.AlterField(
            model_name='produit',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='location.ville'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='location.commune'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='quartier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='location.quartier'),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs', to='location.ville'),
        ),
    ]
