# Generated by Django 5.2.7 on 2026-06-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0003_alter_vendeur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_hex', models.CharField(blank=True, help_text='Code hexadécimal, ex : #FF0000', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProduitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marche/produits/images/')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='0 = affiché en premier')),
                ('principale', models.BooleanField(default=False, help_text='Image mise en avant sur la fiche produit')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('couleur', models.ForeignKey(blank=True, help_text='Couleur associée à cette vue du produit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='marche.couleur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marche.produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
