# Generated by Django 5.2.15 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0004_couleur_produitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_promo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promotionnel'),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début promotion'),
        ),
        migrations.AddField(
            model_name='produit',
            name='promo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin promotion'),
        ),
    ]
