# Generated by Django 5.2.15 on 2026-06-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
        ('marche', '0005_produit_prix_promo_produit_promo_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='boutique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeurs_marche', to='boutique.boutique', verbose_name='Boutique (nouveau système)'),
        ),
    ]
