# Generated by Django 5.2.7 on 2025-11-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('icon_name', models.CharField(blank=True, help_text="Nom de l’icône Material Symbols (ex : 'groups', 'settings', 'home')", max_length=50, null=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text='Ordre d’affichage sur le site/app')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de service',
                'verbose_name_plural': 'Catégories de services',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('avantages', models.TextField(blank=True, help_text='Liste des avantages ou détails marketing du service')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de réduction (0-100)', max_digits=5)),
                ('delai_moyen', models.IntegerField(help_text='Durée moyenne en jours')),
                ('actif', models.BooleanField(default=True)),
                ('populaire', models.BooleanField(default=False, help_text='Afficher ce service en avant sur la page d’accueil')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon_name', models.CharField(blank=True, help_text="Nom de l’icône Material Symbols (ex : 'groups', 'settings', 'home')", max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-populaire', 'nom'],
            },
        ),
    ]
