# Generated by Django 5.2.7 on 2025-11-03 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/extra/')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Ordre d’affichage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'Image associée',
                'verbose_name_plural': 'Images associées',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('contenu', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Ordre d’affichage du texte')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textes', to='services.service')),
            ],
            options={
                'verbose_name': 'Texte associé',
                'verbose_name_plural': 'Textes associés',
                'ordering': ['ordre'],
            },
        ),
    ]
