# Generated by Django 5.2.7 on 2025-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceimage_servicetexte'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetexte',
            name='nombre_documents',
            field=models.PositiveIntegerField(default=1, help_text='Nombre de documents à traiter'),
        ),
        migrations.AddField(
            model_name='servicetexte',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Prix spécifique pour ce pack', max_digits=8),
        ),
    ]
