# Generated by Django 5.2.7 on 2026-06-10 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='perruque.category')),
            ],
        ),
        migrations.CreateModel(
            name='WigProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix promotionnel')),
                ('description', models.TextField(verbose_name='Description')),
                ('color', models.CharField(max_length=100, verbose_name='Couleur')),
                ('length', models.CharField(help_text='Exemple : 10", 12", 14"', max_length=50, verbose_name='Longueur')),
                ('texture', models.CharField(choices=[('straight', 'Lisse'), ('curly', 'Bouclée'), ('wavy', 'Ondulée'), ('kinky', 'Kinky'), ('body_wave', 'Body Wave'), ('deep_wave', 'Deep Wave')], max_length=30, verbose_name='Texture')),
                ('material', models.CharField(choices=[('natural', 'Naturelle'), ('synthetic', 'Synthétique')], max_length=20, verbose_name='Matière')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('video', models.FileField(blank=True, null=True, upload_to='wigs/videos/', verbose_name='Vidéo de présentation')),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('delivery_available', models.BooleanField(default=True, verbose_name='Livraison disponible')),
                ('average_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note moyenne')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'avis")),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('out_of_stock', 'Rupture de stock'), ('preorder', 'Précommande')], default='available', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='perruque.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shopping.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopping/products/images/')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='0 = image principale')),
                ('principale', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='shopping.couleur')),
                ('tailles', models.ManyToManyField(blank=True, related_name='product', to='shopping.taille')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='perruque.wigproduct')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
