# Generated by Django 5.2.15 on 2026-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perruque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wigproduct',
            name='promo_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début promotion'),
        ),
        migrations.AddField(
            model_name='wigproduct',
            name='promo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin promotion'),
        ),
    ]
