# Generated by Django 5.2.7 on 2026-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perruque', '0003_alter_wigproduct_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wigproduct',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Couleur'),
        ),
    ]
