# Generated by Django 5.2.7 on 2025-11-06 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours de traitement'), ('attente_client', 'En attente du client'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='ouvert', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20)),
                ('categorie', models.CharField(blank=True, help_text='Ex: Facturation, Technique, Support Client...', max_length=100, null=True)),
                ('reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('assigné_a', models.ForeignKey(blank=True, help_text='Employé responsable du suivi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Ticket d'assistance",
                'verbose_name_plural': "Tickets d'assistance",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='support/files/')),
                ('visible_par_client', models.BooleanField(default=True, help_text='Permet de masquer un message interne')),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('modifie', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'verbose_name': 'Message de ticket',
                'verbose_name_plural': 'Messages de ticket',
                'ordering': ['date_message'],
            },
        ),
    ]
