# Generated by Django 5.2.7 on 2025-11-07 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('professionnel', 'Professionnel')], default='debutant', max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree', models.CharField(help_text='Ex: 3 jours, 2 semaines', max_length=50)),
                ('mode', models.CharField(choices=[('en_ligne', 'En ligne'), ('presentiel', 'Présentiel'), ('hybride', 'Hybride')], default='en_ligne', max_length=20)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='courses/covers/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nombre_participants', models.PositiveIntegerField(default=0)),
                ('certificat_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('capacite_max', models.PositiveIntegerField(default=30)),
                ('inscrits', models.PositiveIntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='ouverte', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.course')),
                ('formateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_formateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de cours',
                'verbose_name_plural': 'Sessions de cours',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné'), ('attente_paiement', 'En attente de paiement')], default='inscrit', max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('certificat_lien', models.URLField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cours.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cours', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_session', to='cours.coursesession')),
            ],
            options={
                'verbose_name': 'Inscription à un cours',
                'verbose_name_plural': 'Inscriptions aux cours',
                'ordering': ['-date_inscription'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
