# Generated by Django 5.2.7 on 2025-11-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('duree_video', models.CharField(blank=True, max_length=20, null=True)),
                ('ressource_pdf', models.FileField(blank=True, null=True, upload_to='courses/pdf/')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('transcript_auto', models.TextField(blank=True, help_text='Transcription automatique IA', null=True)),
                ('retro_ai', models.TextField(blank=True, help_text='Analyse IA du contenu vidéo', null=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='cours.chapter')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['ordre'],
            },
        ),
    ]
