# Generated by Django 5.2.7 on 2025-11-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_knowledgecheck_chapterprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecheck',
            name='choix',
            field=models.JSONField(default=list, help_text="Ex: [{'reponse':'A', 'texte':'Option A'},...]"),
        ),
    ]
