# Generated by Django 5.2.7 on 2025-11-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_alter_knowledgecheck_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='presentation_ai',
            field=models.TextField(blank=True, help_text='Résumé automatique IA du contenu du cours', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_intro',
            field=models.URLField(blank=True, help_text='Vidéo d’introduction publique du cours', null=True),
        ),
    ]
