# Generated by Django 5.2.7 on 2025-11-07 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_servicetexte_nombre_documents_servicetexte_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_public', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('secteur', models.CharField(max_length=150)),
                ('email_contact', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('note_globale', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_commandes', models.PositiveIntegerField(default=0)),
                ('commentaire_interne', models.TextField(blank=True, help_text="Notes internes non visibles par l'entreprise", null=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forfait', models.CharField(blank=True, help_text='Nom du pack ou du plan tarifaire', max_length=100, null=True)),
                ('tarif_personnalise', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description_forfait', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('date_renouvellement', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_personnalises', to='companies.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises_associees', to='services.service')),
            ],
            options={
                'verbose_name': "Service personnalisé d'entreprise",
                'verbose_name_plural': "Services personnalisés d'entreprises",
                'ordering': ['-date_creation'],
                'unique_together': {('company', 'service')},
            },
        ),
    ]
