# Generated by Django 5.2.7 on 2026-06-10 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0002_product_prix_promo_product_promo_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('seats', models.PositiveIntegerField(verbose_name='Nombre de places')),
                ('doors', models.PositiveIntegerField(verbose_name='Nombre de portes')),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=20)),
                ('fuel', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=20)),
                ('air_conditioning', models.BooleanField(default=True)),
                ('luggage_capacity', models.PositiveIntegerField(default=0, verbose_name='Capacité bagages')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix par jour')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Louée'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiture', to='shopping.shop')),
            ],
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='voiture.car')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shopping/products/images/')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='0 = image principale')),
                ('principale', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_voiture', to='shopping.couleur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voiture.car')),
                ('tailles', models.ManyToManyField(blank=True, related_name='voiture_images', to='shopping.taille')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
