# Generated by Django 5.2.15 on 2026-06-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_prix_promo_product_promo_debut_and_more'),
        ('voiture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône emoji')),
            ],
            options={
                'verbose_name': 'Catégorie de véhicule',
                'verbose_name_plural': 'Catégories de véhicules',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_at'], 'verbose_name': 'Véhicule', 'verbose_name_plural': 'Véhicules'},
        ),
        migrations.AlterModelOptions(
            name='caravailability',
            options={'verbose_name': 'Plage de disponibilité', 'verbose_name_plural': 'Plages de disponibilité'},
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='car',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caution (FCFA)'),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_included',
            field=models.BooleanField(default=False, verbose_name='Chauffeur inclus'),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu de prise en charge'),
        ),
        migrations.AddField(
            model_name='car',
            name='promo_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Début promotion'),
        ),
        migrations.AddField(
            model_name='car',
            name='promo_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fin promotion'),
        ),
        migrations.AlterField(
            model_name='car',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='car',
            name='air_conditioning',
            field=models.BooleanField(default=True, verbose_name='Climatisation'),
        ),
        migrations.AlterField(
            model_name='car',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix / jour (FCFA)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(default=4, verbose_name='Nombre de portes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=20, verbose_name='Carburant'),
        ),
        migrations.AlterField(
            model_name='car',
            name='luggage_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacité bagages (valises)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix promo / jour (FCFA)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voiture', to='shopping.shop', verbose_name='Agence / Propriétaire'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('rented', 'Louée'), ('maintenance', 'En maintenance')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=20, verbose_name='Transmission'),
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='available_from',
            field=models.DateField(verbose_name='Disponible du'),
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='available_to',
            field=models.DateField(verbose_name='Au'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='voiture.carcategory', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='voiture/images/', verbose_name='Photo')),
                ('principale', models.BooleanField(default=False, verbose_name='Photo principale')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='voiture.car', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Photo du véhicule',
                'verbose_name_plural': 'Photos du véhicule',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_jours', models.PositiveIntegerField(verbose_name='Nombre de jours')),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix total (FCFA)')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='Statut')),
                ('message_client', models.TextField(blank=True, verbose_name='Message du client')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='voiture.car', verbose_name='Véhicule')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_voiture', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
