# Generated by Django 5.2.7 on 2025-12-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
