# Generated by Django 5.2.7 on 2025-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes/'),
        ),
    ]
