# Generated by Django 5.2.7 on 2025-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
