# Generated by Django 5.2.7 on 2025-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_alter_dish_created_at_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
