# Generated by Django 5.2.7 on 2025-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_remove_dish_ingredients_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='resto.ingredient'),
        ),
    ]
