# Generated by Django 5.2.7 on 2026-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0009_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
