# Generated by Django 5.2.7 on 2026-04-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0011_remove_ingredient_image_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
