# Generated by Django 5.2.7 on 2026-04-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0012_order_qr_code_order_qr_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_validated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_validated_at',
        ),
    ]
