# Generated by Django 5.2.15 on 2026-06-09 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0021_order_delivery_lat_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='resto_order_status_014ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='resto_order_user_id_188fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['livreur', 'status'], name='resto_order_livreur_77c434_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='resto_order_created_7eb8e4_idx'),
        ),
    ]
