# Generated by Django 5.2.15 on 2026-06-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0023_add_restaurant_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livreurprofile',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
