# Generated by Django 5.2.15 on 2026-06-11 21:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('marche', '0005_produit_prix_promo_produit_promo_debut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la boutique')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone boutique')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/logos/', verbose_name='Logo')),
                ('type_commerce', models.CharField(blank=True, choices=[('marche', 'Faire le marché'), ('shopping', 'Shopping'), ('quincaillerie', 'Quincaillerie'), ('perruque', 'Perruques & beauté'), ('electronique', 'Électronique'), ('mode', 'Mode'), ('pharmacie', 'Pharmacie'), ('restaurant', 'Restaurant'), ('elevage', 'Élevage'), ('voiture', 'Location voiture'), ('immobilier', 'Immobilier'), ('autre', 'Autre')], max_length=30, verbose_name='Type de commerce')),
                ('adresse_exacte', models.CharField(blank=True, max_length=300, verbose_name='Adresse exacte')),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Cliquez sur la carte pour placer la boutique', null=True, srid=4326, verbose_name='Position GPS')),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour bloquer et masquer tous les produits', verbose_name='Active')),
                ('raison_blocage', models.TextField(blank=True, verbose_name='Raison du blocage')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='location.commune', verbose_name='Commune')),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='marche.marche', verbose_name='Marché')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='location.quartier', verbose_name='Quartier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_boutiques', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
                ('ville', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boutiques', to='location.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['actif'], name='boutique_bo_actif_b2e49f_idx'), models.Index(fields=['user', 'actif'], name='boutique_bo_user_id_c56d1d_idx'), models.Index(fields=['ville', 'commune'], name='boutique_bo_ville_i_f654d8_idx')],
            },
        ),
    ]
